<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TESTING-nasr-PC" name="scenarios.mobileweb.Homepage" tests="6" failures="0" timestamp="21 Aug 2020 15:48:08 GMT" time="2.220" errors="6">
  <testcase name="homeComponants_C397911" time="2.173" classname="scenarios.mobileweb.Homepage">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Utilities.Utility.takeScreenshot(Utility.java:97)
at scenarios.mobileweb.Homepage.homeComponants_C397911(Homepage.java:158)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- homeComponants_C397911 -->
  <testcase name="expressReorder_C397912" time="0.000" classname="scenarios.mobileweb.Homepage">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: expressReorder_C397912([Parameter{index=0, type=java.util.Map, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {LaterToday0=Later Today, Time0=0.208333333333333, Username0=web1@gmail.com, VehicalName0=SUV, Asap0=ASAP Order, InStorePickup0=IN_STORE, Password0=Web1@1229, Address0=Linton, VehicalColor0=Black, CurbsidePickup0=CURBSIDE, LintonAddress0=IN, USA}]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: expressReorder_C397912([Parameter{index=0, type=java.util.Map, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {LaterToday0=Later Today, Time0=0.208333333333333, Username0=web1@gmail.com, VehicalName0=SUV, Asap0=ASAP Order, InStorePickup0=IN_STORE, Password0=Web1@1229, Address0=Linton, VehicalColor0=Black, CurbsidePickup0=CURBSIDE, LintonAddress0=IN, USA}]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- expressReorder_C397912 -->
  <testcase name="lastOrder_C397914" time="0.016" classname="scenarios.mobileweb.Homepage">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: lastOrder_C397914([Parameter{index=0, type=java.util.Map, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {LaterToday0=Later Today, Time0=0.208333333333333, Username0=web1@gmail.com, VehicalName0=SUV, Asap0=ASAP Order, InStorePickup0=IN_STORE, Password0=Web1@1229, Address0=Linton, VehicalColor0=Black, CurbsidePickup0=CURBSIDE, LintonAddress0=IN, USA}]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: lastOrder_C397914([Parameter{index=0, type=java.util.Map, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {LaterToday0=Later Today, Time0=0.208333333333333, Username0=web1@gmail.com, VehicalName0=SUV, Asap0=ASAP Order, InStorePickup0=IN_STORE, Password0=Web1@1229, Address0=Linton, VehicalColor0=Black, CurbsidePickup0=CURBSIDE, LintonAddress0=IN, USA}]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- lastOrder_C397914 -->
  <testcase name="viewAll_RedirectedOrderHistory_C397915" time="0.000" classname="scenarios.mobileweb.Homepage">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: viewAll_RedirectedOrderHistory_C397915([Parameter{index=0, type=java.util.Map, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {LaterToday0=Later Today, Time0=0.208333333333333, Username0=web1@gmail.com, VehicalName0=SUV, Asap0=ASAP Order, InStorePickup0=IN_STORE, Password0=Web1@1229, Address0=Linton, VehicalColor0=Black, CurbsidePickup0=CURBSIDE, LintonAddress0=IN, USA}]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: viewAll_RedirectedOrderHistory_C397915([Parameter{index=0, type=java.util.Map, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {LaterToday0=Later Today, Time0=0.208333333333333, Username0=web1@gmail.com, VehicalName0=SUV, Asap0=ASAP Order, InStorePickup0=IN_STORE, Password0=Web1@1229, Address0=Linton, VehicalColor0=Black, CurbsidePickup0=CURBSIDE, LintonAddress0=IN, USA}]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- viewAll_RedirectedOrderHistory_C397915 -->
  <testcase name="noExpressReorder_C397916" time="0.016" classname="scenarios.mobileweb.Homepage">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: noExpressReorder_C397916([Parameter{index=0, type=java.util.Map, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {LaterToday0=Later Today, Time0=0.208333333333333, Username0=web1@gmail.com, VehicalName0=SUV, Asap0=ASAP Order, InStorePickup0=IN_STORE, Password0=Web1@1229, Address0=Linton, VehicalColor0=Black, CurbsidePickup0=CURBSIDE, LintonAddress0=IN, USA}]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: noExpressReorder_C397916([Parameter{index=0, type=java.util.Map, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {LaterToday0=Later Today, Time0=0.208333333333333, Username0=web1@gmail.com, VehicalName0=SUV, Asap0=ASAP Order, InStorePickup0=IN_STORE, Password0=Web1@1229, Address0=Linton, VehicalColor0=Black, CurbsidePickup0=CURBSIDE, LintonAddress0=IN, USA}]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- noExpressReorder_C397916 -->
  <testcase name="reorder_RedirectedtoCart_C397917" time="0.015" classname="scenarios.mobileweb.Homepage">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: reorder_RedirectedtoCart_C397917([Parameter{index=0, type=java.util.Map, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {LaterToday0=Later Today, Time0=0.208333333333333, Username0=web1@gmail.com, VehicalName0=SUV, Asap0=ASAP Order, InStorePickup0=IN_STORE, Password0=Web1@1229, Address0=Linton, VehicalColor0=Black, CurbsidePickup0=CURBSIDE, LintonAddress0=IN, USA}]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: reorder_RedirectedtoCart_C397917([Parameter{index=0, type=java.util.Map, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {LaterToday0=Later Today, Time0=0.208333333333333, Username0=web1@gmail.com, VehicalName0=SUV, Asap0=ASAP Order, InStorePickup0=IN_STORE, Password0=Web1@1229, Address0=Linton, VehicalColor0=Black, CurbsidePickup0=CURBSIDE, LintonAddress0=IN, USA}]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- reorder_RedirectedtoCart_C397917 -->
</testsuite> <!-- scenarios.mobileweb.Homepage -->
