<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TESTING-nasr-PC" name="LMS_Scenarios.LMS_Cheque_Realize" tests="8" failures="1" timestamp="29 May 2020 02:36:07 GMT" time="389.046" errors="0">
  <testcase name="TC001_LaunchBrowser" time="7.791" classname="LMS_Scenarios.LMS_Cheque_Realize">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at LMS_Scenarios.LMS_Cheque_Realize.TC001_LaunchBrowser(LMS_Cheque_Realize.java:164)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC001_LaunchBrowser -->
  <testcase name="TC001_PaymentVerification_BeforePayment" time="60.735" classname="LMS_Scenarios.LMS_Cheque_Realize"/>
  <testcase name="TC002_ReceiptMaker" time="75.044" classname="LMS_Scenarios.LMS_Cheque_Realize"/>
  <testcase name="TC003_DepositMaker" time="49.104" classname="LMS_Scenarios.LMS_Cheque_Realize"/>
  <testcase name="TC004_RealizationMaker" time="47.145" classname="LMS_Scenarios.LMS_Cheque_Realize"/>
  <testcase name="TC005_RealizationMaker" time="48.781" classname="LMS_Scenarios.LMS_Cheque_Realize"/>
  <testcase name="TC006_RealizationApprover" time="37.980" classname="LMS_Scenarios.LMS_Cheque_Realize"/>
  <testcase name="TC007_PaymentVerificatiion" time="62.466" classname="LMS_Scenarios.LMS_Cheque_Realize"/>
</testsuite> <!-- LMS_Scenarios.LMS_Cheque_Realize -->
