<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="TESTING-029" name="BL_main.BL_End2End_50_1_main" tests="6" failures="1" timestamp="10 Oct 2019 07:06:05 GMT" time="129.389" errors="0">
  <testcase name="BrowserLaunch" time="2.203" classname="BL_main.BL_End2End_50_1_main"/>
  <testcase name="TC_CreditLevels" time="91.532" classname="BL_main.BL_End2End_50_1_main"/>
  <testcase name="TC_SalesManager" time="35.654" classname="BL_main.BL_End2End_50_1_main">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at BL_main.BL_End2End_50_1_main.TC_SalesManager(BL_End2End_50_1_main.java:448)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_SalesManager -->
  <testcase name="TC_CRA_1" classname="BL_main.BL_End2End_50_1_main">
    <skipped/>
  </testcase> <!-- TC_CRA_1 -->
  <testcase name="TC_QC" classname="BL_main.BL_End2End_50_1_main">
    <skipped/>
  </testcase> <!-- TC_QC -->
  <testcase name="LoginApplication" classname="BL_main.BL_End2End_50_1_main">
    <skipped/>
  </testcase> <!-- LoginApplication -->
</testsuite> <!-- BL_main.BL_End2End_50_1_main -->
